// Import Dependencies
import { createColumnHelper } from "@tanstack/react-table";
import dayjs from "dayjs";

// Local Imports
import { RowActions } from "./RowActions";
import {
  SelectCell,
  SelectHeader,
} from "components/shared/table/SelectCheckbox";

const columnHelper = createColumnHelper();

export const columns = [
  columnHelper.display({
    id: "select",
    header: SelectHeader,
    cell: SelectCell,
    enableColumnFilter: false,
  }),

  // PHP: Id
  columnHelper.accessor("id", {
    id: "id",
    header: "Id",
    cell: (info) => info.getValue(),
  }),

  // PHP: P.O Number
  columnHelper.accessor("po_number", {
    id: "po_number",
    header: "P.O Number",
    cell: (info) => info.getValue(),
    filterFn: (row, columnId, filterValue) => {
      if (!filterValue || filterValue === "3") return true; // All
      const status = Number(row.original.status);
      if (filterValue === "1") return status === 1; // Approved
      if (filterValue === "2") return status === -1 || status === 0; // Unapproved/Pending
      return true;
    },
    meta: {
      filterType: "select",
      filterOptions: [
        { value: "3", label: "All" },
        { value: "1", label: "Approved" },
        { value: "2", label: "Unapproved" },
      ],
    },
  }),

  // PHP: Generated By
  columnHelper.accessor("addedBy", {
    id: "generated_by",
    header: "Generated By",
    cell: (info) => info.getValue(),
  }),

  // PHP: Vendor Name
  columnHelper.accessor("company", {
    id: "vendor_name",
    header: "Vendor Name",
    cell: (info) => {
      const company = info.getValue() || "";
      const sname = info.row.original.sname || "";
      const text = (company && sname) ? `${company} (${sname})` : (company || sname || "");
      return (
        <div className="whitespace-normal break-words min-w-[150px] max-w-[250px]">
          {text}
        </div>
      );
    },
  }),

  // PHP: Prepared by
  columnHelper.accessor("addedBy", {
    id: "prepared_by",
    header: "Prepared by",
    cell: (info) => info.getValue(),
  }),

  // PHP: Approved by
  columnHelper.accessor("approvedBy", {
    id: "approved_by",
    header: "Approved by",
    cell: (info) => info.getValue(),
  }),

  // PHP: Added On
  columnHelper.accessor("added_on", {
    id: "added_on",
    header: "Added On",
    cell: (info) => {
      const date = info.getValue();
      if (!date) return "";
      return dayjs(date).format("DD/MM/YYYY");
    },
  }),

  // PHP: Action
  columnHelper.display({
    id: "actions",
    header: () => (
      <div className="flex items-center justify-center">Action</div>
    ),
    cell: RowActions,
    enableColumnFilter: false,
  }),
];
