export const UNCERTAINTY_LAYOUTS = {
  ctg: [
    { key: "srno", group: "Type A Factor", header: "Sr No", value: (row) => row.srNo },
    { key: "matrixtype", group: "Type A Factor", header: "Type Of Measurement", value: (row) => row.typeOfMeasurement },
    { key: "uuc0", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "uuc1", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "uuc2", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "uuc3", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "uuc4", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "testunit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "testpoint", group: "Type A Factor", header: "Calibration Point", value: (row) => row.calibrationPoint },
    { key: "averageuuc", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "repeatability", group: "Type A Factor", header: "Std Deviation", value: (row) => row.stdDeviation },
    { key: "typea", group: "Type A Factor", header: "Type A", value: (row) => row.typeA },
    { key: "masterunc", group: "Type B Factor", header: "Uncertainty of Master in mm", value: (row) => row.uncertaintyOfMaster },
    { key: "leastcount", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCount },
    { key: "thermalcomaster", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => row.thermalCoeffMaster },
    { key: "thermalcouuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => row.thermalCoeffUuc },
    { key: "uncertaintytempdevicemm", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => row.uncTempDevice },
    { key: "stduncthercof20", group: "Type B Factor", header: "Standard uncertainty due to the thermal coefficient of expansion master and Unit Under Calibration assuming 20% (mm)", value: (row) => row.stdUncTher20 },
    { key: "stduncdiffinmasuuc", group: "Type B Factor", header: "Standard uncertainty due to the difference in temperature master and Unit Under Calibration assuming 0.5˚C (mm)", value: (row) => row.stdUncDiff },
    { key: "uncduetoerror", group: "Type B Factor", header: "Standard uncertainty due to Error in Master (Taken Half) in mm", value: (row) => row.uncError },
    { key: "comuncer", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => row.combinedUnc },
    { key: "dof", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof },
    { key: "coveragefactor", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => row.coverageFactor },
    { key: "expandeduncertainty", group: "Uncertainty Measurement", header: "Expanded Uncertainty", value: (row) => row.expandedUnc + "μm" },
    { key: "cmcuncertainty", group: "Uncertainty Measurement", header: "CMC taken", value: (row) => row.cmc },
  ],
  rtdwi: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_master_1", group: "Type B Factor", header: "Uncertainty of master-1", value: (row) => typeof row.uncertaintyMaster1 === 'number' ? row.uncertaintyMaster1.toFixed(6) : row.uncertaintyMaster1 },
    { key: "uncertainty_of_master_2", group: "Type B Factor", header: "Uncertainty of master-2", value: (row) => typeof row.uncertaintyMaster2Value === 'number' ? row.uncertaintyMaster2Value.toFixed(6) : row.uncertaintyMaster2Value },
    { key: "sensitivity_coefficient", group: "Type B Factor", header: "Sensitivity Coefficient", value: (row) => row.sensitivityCoefficient },
    { key: "uncertainty_of_master_2", group: "Type B Factor", header: "Uncertainty of master-2", value: (row) => typeof row.uncertaintyMaster2Celsius === 'number' ? row.uncertaintyMaster2Celsius.toFixed(6) : row.uncertaintyMaster2Celsius },
    { key: "stability_of_bath", group: "Type B Factor", header: "Stability Of Bath", value: (row) => typeof row.stabilityBath === 'number' ? row.stabilityBath.toFixed(6) : row.stabilityBath },
    { key: "uniformity_of_bath", group: "Type B Factor", header: "Uniformity Of Bath", value: (row) => typeof row.uniformityBath === 'number' ? row.uniformityBath.toFixed(6) : row.uniformityBath },
    { key: "drift_of_master", group: "Type B Factor", header: "Drift Of Master", value: (row) => typeof row.driftMaster === 'number' ? row.driftMaster.toFixed(6) : row.driftMaster },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUncertainty === 'number' ? row.combinedUncertainty.toFixed(6) : row.combinedUncertainty },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.degreeOfFreedom === '-' ? '-' : (typeof row.degreeOfFreedom === 'number' ? row.degreeOfFreedom.toFixed(2) : row.degreeOfFreedom) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUncertaintyValue === 'number' ? row.expandedUncertaintyValue.toFixed(6) : row.expandedUncertaintyValue },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CmC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(6) : row.cmcTaken },
  ],
  msr: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "type_of_measurement", group: "Type A Factor", header: "Type Of Measurement", value: (row) => row.typeOfMeasurement },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type B Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_slip_gauge_in_mm", group: "Type B Factor", header: "Uncertainty of Slip Gauge in mm", value: (row) => typeof row.uncertaintySlipGauge === 'number' ? row.uncertaintySlipGauge.toFixed(6) : row.uncertaintySlipGauge },
    { key: "uncertainty_of_dial_gauge_in_mm", group: "Type B Factor", header: "Uncertainty of Dial Gauge in mm", value: (row) => typeof row.uncertaintyDialGauge === 'number' ? row.uncertaintyDialGauge.toFixed(6) : row.uncertaintyDialGauge },
    { key: "flatness_of_comparator_stand_in_mm", group: "Type B Factor", header: "Flatness of Comparator Stand in mm", value: (row) => typeof row.flatnessComparatorStand === 'number' ? row.flatnessComparatorStand.toFixed(6) : row.flatnessComparatorStand },
    { key: "least_count_of_master", group: "Type B Factor", header: "Least Count of Master", value: (row) => typeof row.leastCountMaster === 'number' ? row.leastCountMaster.toFixed(6) : row.leastCountMaster },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc },
    { key: "uncertainty_due_to_temperature_indi_z86b", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice },
    { key: "standard_uncertainty_due_to_the_the_sc0o", group: "Type B Factor", header: "Standard uncertainty due to the thermal coefficient of expansion master and Unit Under Calibration assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 },
    { key: "standard_uncertainty_due_to_the_dif_ll5h", group: "Type B Factor", header: "Standard uncertainty due to the difference in temperature master and Unit Under Calibration assuming 0.5˚C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff },
    { key: "standard_uncertainty_due_to_error_i_n1ye", group: "Type B Factor", header: "Standard uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc },
  ],
  dg: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "reading_on_inc_1", group: "Type A Factor", header: "Reading on inc 1", value: (row) => row.readingInc1 },
    { key: "reading_on_dec_2", group: "Type A Factor", header: "Reading on Dec 2", value: (row) => row.readingDec2 },
    { key: "reading_on_inc_3", group: "Type A Factor", header: "Reading on Inc 3", value: (row) => row.readingInc3 },
    { key: "reading_on_dec_4", group: "Type A Factor", header: "Reading on Dec 4", value: (row) => row.readingDec4 },
    { key: "error_in_inc", group: "Type A Factor", header: "Error in inc", value: (row) => typeof row.errorInc === 'number' ? row.errorInc.toFixed(3) : row.errorInc },
    { key: "error_in_dec", group: "Type A Factor", header: "Error in Dec", value: (row) => typeof row.errorDec === 'number' ? row.errorDec.toFixed(3) : row.errorDec },
    { key: "hysterisis", group: "Type A Factor", header: "Hysterisis", value: (row) => typeof row.hysterisis === 'number' ? row.hysterisis.toFixed(3) : row.hysterisis },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => typeof row.average === 'number' ? row.average.toFixed(3) : row.average },
    { key: "std_deviation", group: "Type B Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type B Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_slip_gauge_in_mm", group: "Type B Factor", header: "Uncertainty of Slip Gauge in mm", value: (row) => typeof row.uncertaintySlipGauge === 'number' ? row.uncertaintySlipGauge.toFixed(6) : row.uncertaintySlipGauge },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc },
    { key: "uncertainty_due_to_temperature_indi_w6a5", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice },
    { key: "standard_uncertainty_due_to_the_the_tr5v", group: "Type B Factor", header: "Standard uncertainty due to the thermal coefficient of expansion master and Unit Under Calibration assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 },
    { key: "standard_uncertainty_due_to_the_dif_ekke", group: "Type B Factor", header: "Standard uncertainty due to the difference in temperature master and Unit Under Calibration assuming 0.5˚C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff },
    { key: "standard_uncertainty_due_to_error_i_xhar", group: "Type B Factor", header: "Standard uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CmC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(6) : row.cmcTaken },
    { key: "cmc_scope", group: "Uncertainty Measurement", header: "CmC Scope", value: (row) => typeof row.cmcScope === 'number' ? row.cmcScope.toFixed(6) : row.cmcScope },
  ],
  mg: [
    { key: "m1", group: "Sr no", header: "M1", value: (row) => row.srNo },
    { key: "m2", group: "Set Pressure on UUC", header: "M2", value: (row) => row.setPressure },
  ],
  exm: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "type_of_measurement", group: "Type A Factor", header: "Type Of Measurement", value: (row) => row.typeOfMeasurement },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type B Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_slip_gauge_in_mm", group: "Type B Factor", header: "Uncertainty of Slip Gauge in mm", value: (row) => typeof row.uncertaintySlipGauge === 'number' ? row.uncertaintySlipGauge.toFixed(6) : row.uncertaintySlipGauge },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc },
    { key: "uncertainty_due_to_temperature_indi_0vq4", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice },
    { key: "standard_uncertainty_due_to_the_the_r7qy", group: "Type B Factor", header: "Standard uncertainty due to the thermal coefficient of expansion master and Unit Under Calibration assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 },
    { key: "standard_uncertainty_due_to_the_dif_o48k", group: "Type B Factor", header: "Standard uncertainty due to the difference in temperature master and Unit Under Calibration assuming 0.5˚C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff },
    { key: "uncertainty_due_parallelism_in_mm", group: "Type B Factor", header: "Uncertainty Due Parallelism in (mm)", value: (row) => typeof row.uncParallelism === 'number' ? row.uncParallelism.toFixed(6) : row.uncParallelism },
    { key: "standard_uncertainty_due_to_error_i_kwz4", group: "Type B Factor", header: "Standard uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc },
  ],
  gtm: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => typeof row.average === 'number' ? row.average.toFixed(3) : row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_master_1", group: "Type B Factor", header: "Uncertainty of master-1", value: (row) => typeof row.uncertaintyMaster1 === 'number' ? row.uncertaintyMaster1.toFixed(6) : row.uncertaintyMaster1 },
    { key: "uncertainty_of_master_2", group: "Type B Factor", header: "Uncertainty of master-2", value: (row) => typeof row.uncertaintyMaster2Value === 'number' ? row.uncertaintyMaster2Value.toFixed(6) : row.uncertaintyMaster2Value },
    { key: "sensitivity_coefficient", group: "Type B Factor", header: "Sensitivity Coefficient", value: (row) => row.sensitivityCoefficient },
    { key: "uncertainty_of_master_2", group: "Type B Factor", header: "Uncertainty of master-2", value: (row) => typeof row.uncertaintyMaster2Celsius === 'number' ? row.uncertaintyMaster2Celsius.toFixed(6) : row.uncertaintyMaster2Celsius },
    { key: "stability_of_bath", group: "Type B Factor", header: "Stability Of Bath", value: (row) => typeof row.stabilityBath === 'number' ? row.stabilityBath.toFixed(6) : row.stabilityBath },
    { key: "uniformity_of_bath", group: "Type B Factor", header: "Uniformity Of Bath", value: (row) => typeof row.uniformityBath === 'number' ? row.uniformityBath.toFixed(6) : row.uniformityBath },
    { key: "drift_of_master", group: "Type B Factor", header: "Drift Of Master", value: (row) => typeof row.driftMaster === 'number' ? row.driftMaster.toFixed(6) : row.driftMaster },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUncertainty === 'number' ? row.combinedUncertainty.toFixed(6) : row.combinedUncertainty },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.degreeOfFreedom === '-' ? '-' : (typeof row.degreeOfFreedom === 'number' ? row.degreeOfFreedom.toFixed(2) : row.degreeOfFreedom) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUncertaintyValue === 'number' ? row.expandedUncertaintyValue.toFixed(6) : row.expandedUncertaintyValue },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CmC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(6) : row.cmcTaken },
  ],
  tm: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "val_6", group: "Type A Factor", header: "6", value: (row) => row.values[5] },
    { key: "val_7", group: "Type A Factor", header: "7", value: (row) => row.values[6] },
    { key: "val_8", group: "Type A Factor", header: "8", value: (row) => row.values[7] },
    { key: "val_9", group: "Type A Factor", header: "9", value: (row) => row.values[8] },
    { key: "val_10", group: "Type A Factor", header: "10", value: (row) => row.values[9] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => typeof row.average === 'number' ? row.average.toFixed(6) : row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "accuracy_of_calibrator_in_value", group: "Type B Factor", header: "Accuracy Of Calibrator in Value", value: (row) => typeof row.accuracyCalibrator === 'number' ? row.accuracyCalibrator.toFixed(6) : row.accuracyCalibrator },
    { key: "uncertainty_of_master_in_percent", group: "Type B Factor", header: "Uncertainty of master in %", value: (row) => typeof row.uncertaintyMaster === 'number' ? row.uncertaintyMaster.toFixed(6) : row.uncertaintyMaster },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCount },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUncValue === 'number' ? row.expandedUncValue.toFixed(6) : row.expandedUncValue },
    { key: "expanded_uncertainty_in_percent", group: "Uncertainty Measurement", header: "Expanded Uncertainty in %", value: (row) => typeof row.expandedUncPercent === 'number' ? row.expandedUncPercent.toFixed(6) : row.expandedUncPercent },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc },
  ],
  avg: [
    { key: "m1", group: "Sr no", header: "M1", value: (row) => row.srNo },
    { key: "m2", group: "Set Pressure on UUC", header: "M2", value: (row) => row.setPressure },
  ],
  fg: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_master_in_mm", group: "Type B Factor", header: "Uncertainty of Master in (mm)", value: (row) => typeof row.uncertaintyOfMaster === 'number' ? row.uncertaintyOfMaster.toFixed(6) : row.uncertaintyOfMaster },
    { key: "least_count_of_master", group: "Type B Factor", header: "Least Count of master", value: (row) => row.leastCountMaster },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc },
    { key: "uncertainty_due_to_temperature_indi_ownh", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice },
    { key: "standard_uncertainty_due_to_the_the_4jf2", group: "Type B Factor", header: "Standard uncertainty due to the thermal coefficient of expansion master and Unit Under Calibration assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 },
    { key: "standard_uncertainty_due_to_the_dif_2ofs", group: "Type B Factor", header: "Standard uncertainty due to the difference in temperature master and Unit Under Calibration assuming 0.5˚C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff },
    { key: "uncertainty_due_parallelism_in_mm", group: "Type B Factor", header: "Uncertainty Due Parallelism in (mm)", value: (row) => typeof row.uncParallelism === 'number' ? row.uncParallelism.toFixed(6) : row.uncParallelism },
    { key: "standard_uncertainty_due_to_error_i_vobd", group: "Type B Factor", header: "Standard uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc },
  ],
  it: [
    { key: "sr_no", group: "Type A Factor", header: "Sr No", value: (row) => row.srNo },
    { key: "type_of_measurement", group: "Type A Factor", header: "Type Of Measurement", value: (row) => row.matrixType },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration Point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation + "" },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA + "" },
    { key: "uncertainty_of_master_in_mm", group: "Type B Factor", header: "Uncertainty of Master in mm", value: (row) => typeof row.uncertaintyOfMaster === 'number' ? row.uncertaintyOfMaster.toFixed(6) : row.uncertaintyOfMaster + "" },
    { key: "least_count_of_master", group: "Type B Factor", header: "Least Count of Master", value: (row) => row.leastCountMaster },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster + "" },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc + "" },
    { key: "uncertainty_due_to_temperature_indi_xcb1", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice + "" },
    { key: "standard_uncertainty_due_to_the_the_tz2t", group: "Type B Factor", header: "Standard Uncertainty due to the Thermal Coefficient of Expansion Master and Unit Under Calibration assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 + "" },
    { key: "standard_uncertainty_due_to_the_dif_pq13", group: "Type B Factor", header: "Standard Uncertainty due to the Difference in Temperature Master and Unit Under Calibration assuming 0.5°C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff + "" },
    { key: "standard_uncertainty_due_to_error_i_r7fp", group: "Type B Factor", header: "Standard Uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError + "" },
    { key: "combined_uncertainty", group: "Type B Factor", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc + "" },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) + "" },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor + "" },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc + "" },
    { key: "cmc_scope", group: "Uncertainty Measurement", header: "CMC Scope", value: (row) => typeof row.cmcScope === 'number' ? row.cmcScope.toFixed(6) : row.cmcScope + "" },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc + "" },
  ],
  es: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "unit_type", group: "Type A Factor", header: "Unit Type", value: (row) => row.unitType },
    { key: "mode", group: "Type A Factor", header: "Mode", value: (row) => row.mode },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type B Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "accuracy_of_calibrator_in_value", group: "Type B Factor", header: "Accuracy Of Calibrator in Value", value: (row) => typeof row.accuracyCalibrator === 'number' ? row.accuracyCalibrator.toFixed(6) : row.accuracyCalibrator },
    { key: "uncertainty_of_master_in_percent", group: "Type B Factor", header: "Uncertainty of master in %", value: (row) => typeof row.uncertaintyMaster === 'number' ? row.uncertaintyMaster.toFixed(6) : row.uncertaintyMaster },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC/Master", value: (row) => row.leastCount },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUncValue === 'number' ? row.expandedUncValue.toFixed(6) : row.expandedUncValue },
    { key: "expanded_uncertainty_in_percent", group: "Uncertainty Measurement", header: "Expanded Uncertainty in %", value: (row) => typeof row.expandedUncPercent === 'number' ? row.expandedUncPercent.toFixed(6) : row.expandedUncPercent },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(6) : row.cmcTaken },
    { key: "cmc_scope", group: "Uncertainty Measurement", header: "CMC Scope", value: (row) => typeof row.cmcScope === 'number' ? row.cmcScope.toFixed(6) : row.cmcScope },
  ],
  hg: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "type_of_measurement", group: "Type A Factor", header: "Type Of Measurement", value: (row) => row.typeOfMeasurement },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type B Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_master_in_mm", group: "Type B Factor", header: "Uncertainty of master in mm", value: (row) => typeof row.uncertaintyOfMaster === 'number' ? row.uncertaintyOfMaster.toFixed(6) : row.uncertaintyOfMaster },
    { key: "flatness_of_surface_plate_in_mm", group: "Type B Factor", header: "Flatness of Surface plate in (mm)", value: (row) => typeof row.flatnessSurfacePlate === 'number' ? row.flatnessSurfacePlate.toFixed(6) : row.flatnessSurfacePlate },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc },
    { key: "uncertainty_due_to_temperature_indi_cf9r", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice },
    { key: "standard_uncertainty_due_to_the_the_43tb", group: "Type B Factor", header: "Standard uncertainty due to the thermal coefficient of expansion master and Unit Under Calibration assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 },
    { key: "standard_uncertainty_due_to_the_dif_cy71", group: "Type B Factor", header: "Standard uncertainty due to the difference in temperature master and Unit Under Calibration assuming 0.5˚C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff },
    { key: "uncertainty_due_parallelism_in_mm", group: "Type B Factor", header: "Uncertainty Due Parallelism in (mm)", value: (row) => typeof row.uncParallelism === 'number' ? row.uncParallelism.toFixed(6) : row.uncParallelism },
    { key: "standard_uncertainty_due_to_error_i_nkpg", group: "Type B Factor", header: "Standard uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc },
  ],
  ppg: [
    { key: "sr_no", group: null, header: "Sr No", value: (row) => row.srNo },
    { key: "set_pressure_on_uuc", group: null, header: "Set Pressure on UUC", value: (row) => row.setPressure },
    { key: "m1", group: "Observation on master ({masterUnit})", header: "M1", value: (row) => row.masterObservations?.[0] },
    { key: "m2", group: "Observation on master ({masterUnit})", header: "M2", value: (row) => row.masterObservations?.[1] },
    { key: "m3", group: "Observation on master ({masterUnit})", header: "M3", value: (row) => row.masterObservations?.[2] },
    { key: "m4", group: "Observation on master ({masterUnit})", header: "M4", value: (row) => row.masterObservations?.[3] },
    { key: "m5", group: "Observation on master ({masterUnit})", header: "M5", value: (row) => row.masterObservations?.[4] },
    { key: "m6", group: "Observation on master ({masterUnit})", header: "M6", value: (row) => row.masterObservations?.[5] },
  ],
  dpg: [
    { key: "sr_no", group: null, header: "Sr No", value: (row) => row.srNo },
    { key: "set_pressure_on_uuc", group: null, header: "Set Pressure on UUC", value: (row) => row.setPressure },
    { key: "m1", group: null, header: "M1", value: (row) => row.m1 },
    { key: "m2", group: null, header: "M2", value: (row) => row.m2 },
    { key: "m3", group: null, header: "M3", value: (row) => row.m3 },
    { key: "mean_bar", group: null, header: "Mean (bar)", value: (row) => row.mean },
    { key: "error_bar", group: null, header: "Error (bar)", value: (row) => row.error },
    { key: "max_zero_error", group: null, header: "Max Zero Error", value: (row) => row.maxZeroError },
    { key: "hysterisis_bar", group: null, header: "Hysterisis (bar)", value: (row) => row.hysterisis },
    { key: "repeatability_bar", group: null, header: "Repeatability (bar)", value: (row) => row.repeatability },
    { key: "least_count_of_uuc", group: null, header: "Least Count of UUC", value: (row) => row.leastcount },
    { key: "uncertainty_of_master", group: null, header: "Uncertainty of Master", value: (row) => row.masterUncertainty },
    { key: "combined_uncertainty", group: null, header: "Combined Uncertainty", value: (row) => row.combinedUncertainty },
    { key: "degree_of_freedom", group: null, header: "Degree of Freedom", value: (row) => row.degreeOfFreedom },
    { key: "coverage_factor", group: null, header: "Coverage Factor", value: (row) => row.coverageFactor },
    { key: "expanded_uncertainty", group: null, header: "Expanded Uncertainty", value: (row) => row.expandedUncertainty },
    { key: "cmc_taken", group: null, header: "CMC Taken", value: (row) => row.cmcTaken },
  ],
  mm: [
    { key: "sr_no", group: "Uncertainty Type A", header: "Sr No", value: (row) => row.srNo },
    { key: "unit_type", group: "Uncertainty Type A", header: "Unit Type", value: (row) => row.unitType },
    { key: "mode", group: "Uncertainty Type A", header: "Mode", value: (row) => row.mode },
    { key: "uuc_1", group: "Uncertainty Type A", header: "UUC 1", value: (row) => row.uuc0 },
    { key: "uuc_2", group: "Uncertainty Type A", header: "UUC 2", value: (row) => row.uuc1 },
    { key: "uuc_3", group: "Uncertainty Type A", header: "UUC 3", value: (row) => row.uuc2 },
    { key: "uuc_4", group: "Uncertainty Type A", header: "UUC 4", value: (row) => row.uuc3 },
    { key: "uuc_5", group: "Uncertainty Type A", header: "UUC 5", value: (row) => row.uuc4 },
    { key: "unit", group: "Uncertainty Type A", header: "Unit", value: (row) => row.unit },
    { key: "calibration_point", group: "Uncertainty Type A", header: "Calibration Point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Uncertainty Type A", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Uncertainty Type A", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Uncertainty Type B", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "accuracy_of_calibrator", group: "Uncertainty Type B", header: "Accuracy of Calibrator", value: (row) => typeof row.accuracyOfCalibrator === 'number' ? row.accuracyOfCalibrator.toFixed(6) : row.accuracyOfCalibrator },
    { key: "uncertainty_of_master", group: "Uncertainty Type B", header: "Uncertainty of Master", value: (row) => typeof row.uncertaintyOfMaster === 'number' ? row.uncertaintyOfMaster.toFixed(6) : row.uncertaintyOfMaster },
    { key: "least_count_of_uuc", group: "Uncertainty Type B", header: "Least Count of UUC", value: (row) => row.leastCountOfUuc },
    { key: "combined_uncertainty", group: "Combined Uncertainty", header: "Combined Uncertainty", value: (row) => typeof row.combinedUncertainty === 'number' ? row.combinedUncertainty.toFixed(6) : row.combinedUncertainty },
    { key: "degree_of_freedom", group: "Combined Uncertainty", header: "Degree of Freedom", value: (row) => row.degreeOfFreedom === '-' ? '-' : (typeof row.degreeOfFreedom === 'number' ? row.degreeOfFreedom.toFixed(2) : row.degreeOfFreedom) },
    { key: "coverage_factor", group: "Combined Uncertainty", header: "Coverage Factor", value: (row) => row.coverageFactor },
    { key: "expanded_uncertainty_value", group: "Combined Uncertainty", header: "Expanded Uncertainty Value", value: (row) => typeof row.expandedUncertaintyValue === 'number' ? row.expandedUncertaintyValue.toFixed(6) : row.expandedUncertaintyValue },
    { key: "expanded_uncertainty", group: "Combined Uncertainty", header: "Expanded Uncertainty %", value: (row) => typeof row.expandedUncertaintyPercent === 'number' ? row.expandedUncertaintyPercent.toFixed(6) : row.expandedUncertaintyPercent },
    { key: "cmc_taken", group: "Combined Uncertainty", header: "CMC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(6) : row.cmcTaken },
    { key: "cmc_scope", group: "Combined Uncertainty", header: "CMC Scope", value: (row) => typeof row.cmcScope === 'number' ? row.cmcScope.toFixed(6) : row.cmcScope },
  ],
  odfm: [
    { key: "sr_no", group: "Type A Factor", header: "Sr No", value: (row) => row.srNo },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.master0 },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.master1 },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.master2 },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.master3 },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.master4 },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration Point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_master_1_sensor_in_c", group: "Type B Factor", header: "Uncertainty of master 1 sensor in (°C)", value: (row) => typeof row.uncertaintyMaster1 === 'number' ? row.uncertaintyMaster1.toFixed(3) : row.uncertaintyMaster1 },
    { key: "uncertainty_of_master_2_6_5_dmm_in_value", group: "Type B Factor", header: "Uncertainty of master 2 (6.5 DMM) in Value", value: (row) => typeof row.uncertaintyMaster2Value === 'number' ? row.uncertaintyMaster2Value.toFixed(3) : row.uncertaintyMaster2Value },
    { key: "sensitivity_coefficient", group: "Type B Factor", header: "Sensitivity Coefficient", value: (row) => row.sensitivityCoefficient },
    { key: "uncertainty_of_master_2_6_5_dmm_in_c", group: "Type B Factor", header: "Uncertainty of master 2 (6.5 DMM) in °C", value: (row) => typeof row.uncertaintyMaster2Celsius === 'number' ? row.uncertaintyMaster2Celsius.toFixed(3) : row.uncertaintyMaster2Celsius },
    { key: "stability_of_bath_c", group: "Type B Factor", header: "Stability of Bath (°C)", value: (row) => typeof row.stabilityBath === 'number' ? row.stabilityBath.toFixed(3) : row.stabilityBath },
    { key: "uniformity_of_bath_c", group: "Type B Factor", header: "Uniformity Of Bath (°C)", value: (row) => typeof row.uniformityBath === 'number' ? row.uniformityBath.toFixed(3) : row.uniformityBath },
    { key: "drift_in_master_c", group: "Type B Factor", header: "Drift in Master (°C)", value: (row) => typeof row.driftMaster === 'number' ? row.driftMaster.toFixed(3) : row.driftMaster },
    { key: "least_count_of_uuc", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUncertainty === 'number' ? row.combinedUncertainty.toFixed(6) : row.combinedUncertainty },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.degreeOfFreedom === '-' ? '-' : (typeof row.degreeOfFreedom === 'number' ? row.degreeOfFreedom.toFixed(2) : row.degreeOfFreedom) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUncertaintyValue === 'number' ? row.expandedUncertaintyValue.toFixed(6) : row.expandedUncertaintyValue },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmcUncertainty === 'number' ? row.cmcUncertainty.toFixed(6) : row.cmcUncertainty },
  ],
  mt: [
    { key: "sr_no", group: "Type A Factor", header: "Sr No", value: (row) => row.srNo },
    { key: "val_1", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "val_2", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "val_3", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "val_4", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "val_5", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration Point", value: (row) => row.calibrationPoint },
    { key: "average", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "std_deviation", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "type_a", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "uncertainty_of_master_in_mm", group: "Type B Factor", header: "Uncertainty of Master in (mm)", value: (row) => typeof row.uncertaintyOfMaster === 'number' ? row.uncertaintyOfMaster.toFixed(6) : row.uncertaintyOfMaster },
    { key: "thickness_of_graduation_line_mark_i_o1em", group: "Type B Factor", header: "Thickness of Graduation Line Mark in Measuring Tape", value: (row) => row.thicknessOfGraduation },
    { key: "thermal_coefficient_of_master", group: "Type B Factor", header: "Thermal Coefficient of Master", value: (row) => typeof row.thermalCoeffMaster === 'number' ? row.thermalCoeffMaster.toFixed(6) : row.thermalCoeffMaster },
    { key: "thermal_coefficient_of_uuc", group: "Type B Factor", header: "Thermal Coefficient of UUC", value: (row) => typeof row.thermalCoeffUuc === 'number' ? row.thermalCoeffUuc.toFixed(6) : row.thermalCoeffUuc },
    { key: "uncertainty_due_to_temperature_indi_bgfl", group: "Type B Factor", header: "Uncertainty due to Temperature Indicating Device (mm)", value: (row) => typeof row.uncTempDevice === 'number' ? row.uncTempDevice.toFixed(6) : row.uncTempDevice },
    { key: "standard_uncertainty_due_to_thermal_d7cb", group: "Type B Factor", header: "Standard Uncertainty due to Thermal Coefficient of Expansion Master and UUC assuming 20% (mm)", value: (row) => typeof row.stdUncTher20 === 'number' ? row.stdUncTher20.toFixed(6) : row.stdUncTher20 },
    { key: "standard_uncertainty_due_to_differe_pto5", group: "Type B Factor", header: "Standard Uncertainty due to Difference in Temperature Master and UUC assuming 0.5°C (mm)", value: (row) => typeof row.stdUncDiff === 'number' ? row.stdUncDiff.toFixed(6) : row.stdUncDiff },
    { key: "uncertainty_due_to_parallelism_in_mm", group: "Type B Factor", header: "Uncertainty Due to Parallelism in (mm)", value: (row) => typeof row.uncParallelism === 'number' ? row.uncParallelism.toFixed(6) : row.uncParallelism },
    { key: "standard_uncertainty_due_to_error_i_t8sv", group: "Type B Factor", header: "Standard Uncertainty due to Error in Master (Taken Half) in mm", value: (row) => typeof row.uncError === 'number' ? row.uncError.toFixed(6) : row.uncError },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUnc === 'number' ? row.combinedUnc.toFixed(6) : row.combinedUnc },
    { key: "degree_of_freedom", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.dof === '-' ? '-' : (typeof row.dof === 'number' ? row.dof.toFixed(2) : row.dof) },
    { key: "coverage_factor_k", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expanded_uncertainty_in_value", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUnc === 'number' ? row.expandedUnc.toFixed(6) : row.expandedUnc },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmc === 'number' ? row.cmc.toFixed(6) : row.cmc },
  ],
  tswoi: [
    { key: "srno", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "uuc0", group: "Type A Factor", header: "1", value: (row) => row.values[0] },
    { key: "uuc1", group: "Type A Factor", header: "2", value: (row) => row.values[1] },
    { key: "uuc2", group: "Type A Factor", header: "3", value: (row) => row.values[2] },
    { key: "uuc3", group: "Type A Factor", header: "4", value: (row) => row.values[3] },
    { key: "uuc4", group: "Type A Factor", header: "5", value: (row) => row.values[4] },
    { key: "uucunit", group: "Type A Factor", header: "Unit", value: (row) => row.unit + "" },
    { key: "testpoint", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "averageuuc", group: "Type A Factor", header: "Average", value: (row) => row.average },
    { key: "repeatability", group: "Type A Factor", header: "Std Deviation", value: (row) => typeof row.stdDeviation === 'number' ? row.stdDeviation.toFixed(6) : row.stdDeviation },
    { key: "typea", group: "Type A Factor", header: "Type A", value: (row) => typeof row.typeA === 'number' ? row.typeA.toFixed(6) : row.typeA },
    { key: "masterunc", group: "Type B Factor", header: "Uncertainty of master-1 Sensor in °C", value: (row) => typeof row.uncertaintyMaster1 === 'number' ? row.uncertaintyMaster1.toFixed(6) : row.uncertaintyMaster1 },
    { key: "masterunc2", group: "Type B Factor", header: "Uncertainty of master-2 in (6.5DMM) in value", value: (row) => typeof row.uncertaintyMaster2Value === 'number' ? row.uncertaintyMaster2Value.toFixed(6) : row.uncertaintyMaster2Value },
    { key: "sensitivitycoefient", group: "Type B Factor", header: "Sensitivity Coefficient", value: (row) => row.sensitivityCoefficient },
    { key: "masterunc2inc", group: "Type B Factor", header: "Uncertainty of master-2 in (°C)", value: (row) => typeof row.uncertaintyMaster2Celsius === 'number' ? row.uncertaintyMaster2Celsius.toFixed(6) : row.uncertaintyMaster2Celsius },
    { key: "stability", group: "Type B Factor", header: "Stability Of Bath", value: (row) => typeof row.stabilityBath === 'number' ? row.stabilityBath.toFixed(6) : row.stabilityBath },
    { key: "uniformity", group: "Type B Factor", header: "Uniformity Of Bath", value: (row) => typeof row.uniformityBath === 'number' ? row.uniformityBath.toFixed(6) : row.uniformityBath },
    { key: "drift", group: "Type B Factor", header: "Drift Of Master", value: (row) => typeof row.driftMaster === 'number' ? row.driftMaster.toFixed(6) : row.driftMaster },
    { key: "leastcount", group: "Type B Factor", header: "Least Count of UUC", value: (row) => row.leastCountUuc },
    { key: "comuncer", group: "Uncertainty Measurement", header: "Combined Uncertainty", value: (row) => typeof row.combinedUncertainty === 'number' ? row.combinedUncertainty.toFixed(6) : row.combinedUncertainty },
    { key: "dof", group: "Uncertainty Measurement", header: "Degree of Freedom", value: (row) => row.degreeOfFreedom === '-' ? '-' : (typeof row.degreeOfFreedom === 'number' ? row.degreeOfFreedom.toFixed(2) : row.degreeOfFreedom) },
    { key: "coveragefactor", group: "Uncertainty Measurement", header: "Coverage Factor (k)", value: (row) => typeof row.coverageFactor === 'number' ? row.coverageFactor.toFixed(2) : row.coverageFactor },
    { key: "expandeduncertainty", group: "Uncertainty Measurement", header: "Expanded Uncertainty in Value", value: (row) => typeof row.expandedUncertaintyValue === 'number' ? row.expandedUncertaintyValue.toFixed(6) : row.expandedUncertaintyValue },
    { key: "cmcuncertainty", group: "Uncertainty Measurement", header: "CmC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(6) : row.cmcTaken },
  ],
  utm: [
    { key: "sr_no", group: "Type A Factor", header: "Sr no", value: (row) => row.srNo },
    { key: "force", group: "Type A Factor", header: "Force", value: (row) => row.force },
    { key: "mode", group: "Type A Factor", header: "Mode", value: (row) => row.mode },
    { key: "unit", group: "Type A Factor", header: "Unit", value: (row) => row.unit },
    { key: "calibration_point", group: "Type A Factor", header: "Calibration point", value: (row) => row.calibrationPoint },
    { key: "calculateduuc", group: "Type A Factor", header: "Std at 24 ±1 °C", value: (row) => row.calculateduuc },
    { key: "uuc0", group: "Type A Factor", header: "Standard Division at Room temp", value: (row) => row.uuc0 },
    { key: "master0", group: "Observation ON master (In Count)", header: "1", value: (row) => row.master0 },
    { key: "master1", group: "Observation ON master (In Count)", header: "2", value: (row) => row.master1 },
    { key: "master2", group: "Observation ON master (In Count)", header: "3", value: (row) => row.master2 },
    { key: "averagemaster", group: "Observation ON master (In Count)", header: "Average", value: (row) => typeof row.averagemaster === 'number' ? row.averagemaster.toFixed(2) : row.averagemaster },
    { key: "q1", group: "Relative Indicative Error", header: "q1", value: (row) => typeof row.q1Error === 'number' ? row.q1Error.toFixed(2) : row.q1Error },
    { key: "q2", group: "Relative Indicative Error", header: "q2", value: (row) => typeof row.q2Error === 'number' ? row.q2Error.toFixed(2) : row.q2Error },
    { key: "q3", group: "Relative Indicative Error", header: "q3", value: (row) => typeof row.q3Error === 'number' ? row.q3Error.toFixed(2) : row.q3Error },
    { key: "avg_q", group: "Relative Indicative Error", header: "Average", value: (row) => typeof row.avgQError === 'number' ? row.avgQError.toFixed(2) : row.avgQError },
    { key: "diff_q", group: "Type A Factor", header: "Relative indication error q in %", value: (row) => typeof row.diffQError === 'number' ? row.diffQError.toFixed(2) : row.diffQError },
    { key: "urep", group: "Type A Factor", header: "Repatability by Standard Deviation Urep in %", value: (row) => typeof row.urep === 'number' ? row.urep.toFixed(5) : row.urep },
    { key: "leastcount", group: "Type B Factor", header: "Least Count", value: (row) => row.leastcount },
    { key: "maxzeroerror", group: "Type B Factor", header: "Relative Zero error in %", value: (row) => row.maxzeroerror },
    { key: "af", group: "Type B Factor", header: "Relative Resolution aF in %", value: (row) => typeof row.af === 'number' ? row.af.toFixed(4) : row.af },
    { key: "az", group: "Type B Factor", header: "Relative Resolution aZ in %", value: (row) => typeof row.az === 'number' ? row.az.toFixed(5) : row.az },
    { key: "ures", group: "Type B Factor", header: "Resolution UNC(Ures)", value: (row) => typeof row.ures === 'number' ? row.ures.toFixed(5) : row.ures },
    { key: "masterunc", group: "Type B Factor", header: "Master UNC in Certificate in %", value: (row) => row.masterunc },
    { key: "drift", group: "Type B Factor", header: "Drift in %", value: () => "0.00" },
    { key: "ustd", group: "Type B Factor", header: "Master UNC. Uncertainty Ustd in %", value: (row) => typeof row.ustd === 'number' ? row.ustd.toFixed(4) : row.ustd },
    { key: "combined_uncertainty", group: "Uncertainty Measurement", header: "Combined Uncertainty in %", value: (row) => typeof row.combinedUncertainty === 'number' ? row.combinedUncertainty.toFixed(8) : row.combinedUncertainty },
    { key: "kfactor", group: "Uncertainty Measurement", header: "K Factor", value: (row) => row.kfactor },
    { key: "expanded_uncertainty", group: "Uncertainty Measurement", header: "Expanded Uncertainty in %", value: (row) => typeof row.expandedUncertainty === 'number' ? row.expandedUncertainty.toFixed(3) : row.expandedUncertainty },
    { key: "cmc_scope", group: "Uncertainty Measurement", header: "CmC Scope", value: (row) => typeof row.cmcScope === 'number' ? row.cmcScope.toFixed(4) : row.cmcScope },
    { key: "cmc_taken", group: "Uncertainty Measurement", header: "CMC Taken", value: (row) => typeof row.cmcTaken === 'number' ? row.cmcTaken.toFixed(4) : row.cmcTaken },
  ],
};
