// High-Fidelity Mock Complaint Dataset for Customer Complaint List
export const mockComplaints = [
  {
    ref_no: "CCR/2026/0501",
    receipt_date: "2026-05-10",
    customer_name_source: "Acme Calibration Center",
    customercode: "ACC-9018",
    type: "CC",
    complaint_type: "CC",
    add1: "Plot No. 45, Phase III",
    add2: "Industrial Area",
    city: "Indore",
    pincode: "452003",
    state: "Madhya Pradesh",
    concern_name: "Raman Malhotra",
    concernpersonname: "Raman Malhotra",
    concernpersonmobile: "+91 98270 12345",
    concern_mobile: "+91 98270 12345",
    concern_email: "raman@acmecalib.com",
    received_by_date: "S. K. Verma (2026-05-10)",
    registered_by_date: "Priya Sharma (2026-05-11)",
    ref_doc_no: "DOC-9082-REV2",
    nature_details: "Calibration error in digital voltmeter models. Discrepancy observed of 0.5% against NABL standards.",
    is_nc_work: "Yes",
    nccomment: "Voltage standard calibration drift was out of tolerance by 0.5%.",
    capa_assigned: "Vikram Rathore",
    validated_by: "Dr. Anil Mehta",
    rca_date: "2026-05-12",
    status_code: 5,
    status: 5,
    remark: "Root cause identified as minor temperature drift in voltage calibration reference. Equipment re-calibrated.",
  },
  {
    ref_no: "CCR/2026/0502",
    receipt_date: "2026-05-14",
    customer_name_source: "Zenith Bio-Labs",
    customercode: "ZBL-4029",
    type: "CC",
    complaint_type: "CC",
    add1: "Suite 400, Biotech Tower",
    add2: "Science Park",
    city: "Bangalore",
    pincode: "560100",
    state: "Karnataka",
    concern_name: "Dr. Shalini Sen",
    concernpersonname: "Dr. Shalini Sen",
    concernpersonmobile: "+91 98450 99887",
    concern_mobile: "+91 98450 99887",
    concern_email: "shalini@zenithbiolabs.org",
    received_by_date: "R. K. Gupta (2026-05-14)",
    registered_by_date: "R. K. Gupta (2026-05-14)",
    ref_doc_no: "ZBL-TRF-40291",
    nature_details: "Delay in delivering micro-biological culture analysis certificate. Turnaround time exceeded by 4 days.",
    is_nc_work: "No",
    nccomment: "",
    capa_assigned: "Amitesh Pandey",
    validated_by: "Sunita Roy",
    rca_date: "2026-05-16",
    status_code: 1,
    status: 1,
    remark: "Under investigation. Staffing shortage in microbiological testing wing observed during testing week.",
  },
  {
    ref_no: "CCR/2026/0503",
    receipt_date: "2026-05-18",
    customer_name_source: "Kailtech Engineering Works / Audit",
    type: "NC Work",
    complaint_type: "NC Work",
    source: "External NABL Quality Audit 2026",
    concern_name: "John Harrison",
    concernpersonname: "John Harrison",
    concernpersonmobile: "+44 7700 900077",
    concern_mobile: "+44 7700 900077",
    concern_email: "j.harrison@kailtecheng.co.in",
    received_by_date: "S. K. Verma (2026-05-19)",
    registered_by_date: "Priya Sharma (2026-05-19)",
    ref_doc_no: "AUD-EXT-2026-B",
    nature_details: "External audit observation #4. Lack of labels on calibration standard containers.",
    is_nc_work: "Yes",
    nccomment: "NABL Section 4.5 Container compliance tagging missing on primary standard solutions.",
    capa_assigned: "Vikram Rathore",
    validated_by: "Dr. Anil Mehta",
    rca_date: "2026-05-20",
    status_code: 6,
    status: 6,
    remark: "Labels printed and container inventory updated with active NABL tag IDs. Compliance verification complete.",
  },
  {
    ref_no: "CCR/2026/0504",
    receipt_date: "2026-05-22",
    customer_name_source: "Global Laboratories Inc.",
    customercode: "GLI-201",
    type: "CC",
    complaint_type: "CC",
    add1: "5th Avenue, Sector 62",
    city: "Noida",
    pincode: "201301",
    state: "Uttar Pradesh",
    concern_name: "Marcus Vance",
    concernpersonname: "Marcus Vance",
    concernpersonmobile: "+1 555 019 2834",
    concern_mobile: "+1 555 019 2834",
    concern_email: "m.vance@globallabs.com",
    received_by_date: "Priya Sharma (2026-05-23)",
    registered_by_date: "Priya Sharma (2026-05-23)",
    ref_doc_no: "GL-INV-99212",
    nature_details: "Incorrect invoicing of tax slab for multi-point testing contract. Applied 18% instead of special export 5%.",
    is_nc_work: "No",
    nccomment: "",
    capa_assigned: "Sunil Jain (Accounts)",
    validated_by: "Sunita Roy",
    rca_date: "2026-05-24",
    status_code: 2,
    status: 2,
    remark: "Credit note initiated. System database GST structure corrected for foreign entities.",
  },
  {
    ref_no: "CCR/2026/0505",
    receipt_date: "2026-05-25",
    customer_name_source: "Apex Calibration Agency",
    customercode: "ACA-781",
    type: "CC",
    complaint_type: "CC",
    add1: "12, Ring Road",
    add2: "Near Metro Pillar 89",
    city: "New Delhi",
    pincode: "110015",
    state: "Delhi",
    concern_name: "Rahul Deshmukh",
    concernpersonname: "Rahul Deshmukh",
    concernpersonmobile: "+91 99110 55443",
    concern_mobile: "+91 99110 55443",
    concern_email: "rahul.d@apexcalib.net",
    received_by_date: "S. K. Verma (2026-05-25)",
    registered_by_date: "Priya Sharma (2026-05-26)",
    ref_doc_no: "REF-NABL-4021",
    nature_details: "Minor scratch on digital thermometer display during transit. Protective bubble wrap was insufficient.",
    is_nc_work: "Yes",
    nccomment: "Transit bubble wrap thickness was below standard logistics safety guidelines (5mm instead of 10mm).",
    capa_assigned: "Girish Kulkarni (Logistics)",
    validated_by: "Sunita Roy",
    rca_date: "2026-05-27",
    status_code: 5,
    status: 5,
    remark: "Replaced the display glass. Packaging material upgraded to heavy-duty double padding cases for NABL kits.",
  }
];

export const statusMapColors = {
  Open: "text-rose-600 bg-rose-50 border-rose-250 dark:bg-rose-950/20 dark:text-rose-400 dark:border-rose-900/50",
  Closed: "text-emerald-600 bg-emerald-50 border-emerald-250 dark:bg-emerald-950/20 dark:text-emerald-400 dark:border-emerald-900/50",
  Pending: "text-amber-600 bg-amber-50 border-amber-250 dark:bg-amber-950/20 dark:text-amber-400 dark:border-amber-900/50",
  "Under Investigation": "text-sky-600 bg-sky-50 border-sky-250 dark:bg-sky-950/20 dark:text-sky-400 dark:border-sky-900/50"
};
