// High-Fidelity Mock NC Dataset for NC List Dashboard
export const mockNcRecords = [
  {
    id: 1,
    date: "2026-05-10",
    ref_no: "NC/2026/0501",
    source: "NABL External Audit 2026",
    concern_person: "Dr. Anil Mehta (Quality Manager)",
    type: "NC Work",
    status_code: 5,
    status: 5,
    completion_percentage: 100,
    nature_details: "Voltage standard calibration drift was out of tolerance by 0.5% in Section 3.",
    remark: "Calibration equipment re-certified and tag compliance updated.",
  },
  {
    id: 2,
    date: "2026-05-14",
    ref_no: "NC/2026/0502",
    source: "Zenith Bio-Labs / Customer Complaint",
    concern_person: "Dr. Shalini Sen",
    type: "Customer Complaint",
    status_code: 1,
    status: 1,
    completion_percentage: 33,
    nature_details: "Turnaround time for chemical certificate analysis exceeded by 4 working days.",
    remark: "Under investigation. Staffing shortages observed during the target week.",
  },
  {
    id: 3,
    date: "2026-05-18",
    ref_no: "NC/2026/0503",
    source: "Internal Quality Audit - Q2",
    concern_person: "John Harrison (Lead Auditor)",
    type: "NC Work",
    status_code: 6,
    status: 6,
    completion_percentage: 66,
    nature_details: "NABL Section 4.5 container compliance tagging missing on primary standard solutions.",
    remark: "Container standard solution inventory refreshed and tagged.",
  },
  {
    id: 4,
    date: "2026-05-22",
    ref_no: "NC/2026/0504",
    source: "Apex Calibration Agency",
    concern_person: "Rahul Deshmukh (Logistics Head)",
    type: "Customer Complaint",
    status_code: 2,
    status: 2,
    completion_percentage: 0,
    nature_details: "Minor scratch on digital thermometer display due to insufficient bubble wrapping.",
    remark: "Replaced digital display. Upgraded transit logistics packaging box.",
  },
  {
    id: 5,
    date: "2026-05-26",
    ref_no: "NC/2026/0505",
    source: "Global Laboratories Inc.",
    concern_person: "Marcus Vance",
    type: "Customer Complaint",
    status_code: 5,
    status: 5,
    completion_percentage: 100,
    nature_details: "Applied wrong export tax slab (18% instead of 5%) on multi-point contract invoicing.",
    remark: "Credit note processed. Corrected invoice issued.",
  }
];

export const statusCodesMap = {
  0: "RCA is pending",
  1: "RCA is done CAPA submission is pending",
  2: "CAPA submission is done CAPA approval is pending",
  3: "CAPA execution is done CAPA verification is pending",
  4: "CAPA execution is done CAPA verified by QM",
  5: "CAPA has been verified complaint is closed",
  6: "CAPA approval is done CAPA execution is pending",
};

export const statusColorsMap = {
  "RCA is pending": "text-rose-600 bg-rose-50 border-rose-200 dark:bg-rose-950/20 dark:text-rose-400 dark:border-rose-900/50",
  "RCA is done CAPA submission is pending": "text-sky-600 bg-sky-50 border-sky-200 dark:bg-sky-950/20 dark:text-sky-400 dark:border-sky-900/50",
  "CAPA submission is done CAPA approval is pending": "text-indigo-600 bg-indigo-50 border-indigo-200 dark:bg-indigo-950/20 dark:text-indigo-400 dark:border-indigo-900/50",
  "CAPA execution is done CAPA verification is pending": "text-teal-600 bg-teal-50 border-teal-200 dark:bg-teal-950/20 dark:text-teal-400 dark:border-teal-900/50",
  "CAPA execution is done CAPA verified by QM": "text-emerald-600 bg-emerald-50 border-emerald-200 dark:bg-emerald-950/20 dark:text-emerald-400 dark:border-emerald-900/50",
  "CAPA has been verified complaint is closed": "text-green-600 bg-green-50 border-green-200 dark:bg-green-950/20 dark:text-green-400 dark:border-green-900/50",
  "CAPA approval is done CAPA execution is pending": "text-amber-600 bg-amber-50 border-amber-200 dark:bg-amber-950/20 dark:text-amber-400 dark:border-amber-900/50",
};
